### ISSUE TITLE
[프로필 UI]팔로우 버튼 텍스트 세로로 내려감

### ISSUE THREAD

**Issue by newfly101** [PrograMemo-Groom/instagram-clone#34]
![image](https://github.com/user-attachments/assets/a7a6dab4-c4e2-4fd5-89bc-3bad5bb238bc)

**Comment by happygirlll** [comment]
<img width="475" alt="스크린샷 2024-12-26 오후 11 30 40" src="https://github.com/user-attachments/assets/5f3d7719-08ca-49ad-9ab9-e565b15f094b" />

메시지 보내기 버튼도 세로로 됩니당

**Comment by Saaad9** [comment]
확인했고 해결했습니다!
