### ISSUE TITLE
[프로필 UI] 반응형 피드백 있습니다 !

### ISSUE THREAD

**Issue by happygirlll** [PrograMemo-Groom/instagram-clone#35]
작은 너비일 때, 게시물 사진 비율을 1:1로 하시면 더 좋을거 같아 피드백 드립니다 !
머지 이후에 한번 고려 해주세용 ☺️
<br>

> 기존 화면

<img width="458" alt="스크린샷 2024-12-26 오후 11 36 58" src="https://github.com/user-attachments/assets/1ae29628-4879-49f4-befc-ac3ef7176cbf" />

<br><br>

> 변경했으면 하는 화면
<img width="479" alt="스크린샷 2024-12-26 오후 11 35 02" src="https://github.com/user-attachments/assets/c949147f-da6e-4341-95ce-fe2d394000b8" />

**Comment by Saaad9** [comment]
확인입니닷
